In [1]:
import numpy as np
import time 

In [2]:
rng = np.random.default_rng(seed=42)
d = rng.random((1000,3))
d,d.T
d.shape,d.dtype                         #-----> (1000,3), dtype=('float64')
print(d.T.shape)                        #-----> predict: (d.T.shape = 3,1000)

print(d.reshape(3, 1000).shape)         #-----> predict: d.reshape(3, 1000).shape = (3,1000)

print(d.reshape(-1).shape)              #-----> predict: d.reshape(-1).shape = idk

(3, 1000)
(3, 1000)
(3000,)


In [3]:
a = rng.random((2,3))
b = rng.random((2,3))
a,b
a + b

array([[1.41920636, 0.70484631, 0.32436031],
       [1.49651133, 0.3774168 , 1.66371969]])

In [4]:
X = np.array([
    [1, 10],
    [2, 20],
    [3, 30]
])

X_centered = X - X.mean(axis=0)
X.mean(axis=0)

array([ 2., 20.])

In [5]:
arr = rng.random(10_000)

start = time.time()
loop_result = [ x * 2 for x in arr]
loop_time = time.time() - start

start =  time.time()
vec_result = arr * 2
vec_time = time.time() - start

print(f"loop: {loop_time:.5f}s, vectorized: {vec_time:.5f}s, speedup: {loop_time/vec_time:.1f}x")

%timeit loop_result
%timeit vec_result

loop: 0.00146s, vectorized: 0.00017s, speedup: 8.5x
7.48 ns ± 0.139 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
7.51 ns ± 0.245 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [6]:
#boolean masks

arr = np.array([3, 8, 2, 10, 5, 7])

mask1 = arr > 5
mask2 = arr < 5
mask3 = arr == 5

print(arr[mask1])
print(arr[mask3])
print(arr[mask2])

arr2 = [arr[mask1] % arr[mask3]]
arr2

arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])
print(arr[[1,3]])
arr2 = np.array([[20,40,60],[10,30,50]])
print(arr2[[1][0]])



[ 8 10  7]
[5]
[3 2]
[10 30 50]
[20 40]
[10 30 50]


In [7]:
# Axis and stable softmax


In [12]:
rng = np.random.default_rng(0)
m = rng.random((4,3))

print(m.sum(axis=0))   
print(m.sum(axis=1))   

[2.19519752 2.62840707 1.50009259]
[0.94772193 1.74255345 1.87975733 1.75366448]
